Cleaned Experiment/views.py
FOSSEE/SBHS-Vlabs pull request #1
Opened 2017-02-21 17:24 UTC by meshde

Cleared all references to Board,Slot and Booking models in experiment/views.py. Also changed the Experiment model schema to include Foreign Key reference to Account.(Previously, Experiment had foreign key to Booking and Booking in turn had foreign key to Account)

The client is successfully able to connect to the modified local django server on my PC with the message displayed as "Ready to execute Scilab code"

2017-02-24 18:39 UTC, meshde commented
I have also completely changed the sbhs.py file, the getTemp() method now returns the sum of the fan and heat percentages.
The code is working with the scilab experiments and correct output is being displayed in the client application window

I have just commented out the previous codes rather than deleting them.This is to facilitate quick debugging and fixing, I'll be sure to completely clean the code once all possible changes have been made and the code works perfectly

2017-02-26 14:57 UTC, maheshgudi commented on experiments/meshde/2017Feb24_17_32_51.txt
> +6 30 50 80.00 1487937849189 1487937849199 1487937849239 0.60000E+01
Please get rid of these files. They are not useful to a developer.

2017-02-26 15:00 UTC, maheshgudi commented on sbhs_server/experiment/views.py
>  import json, datetime, os, time
Import the modules individually.

2017-02-26 15:04 UTC, maheshgudi commented on sbhs_server/experiment/views.py
> +            #key = str(1)#Temporarily till SBHS class and settings.board dictionary are changed
Get rid of the commented code

2017-02-26 15:13 UTC, maheshgudi commented on sbhs_server/tables/migrations/0008_initial.py
>      def forwards(self, orm):
Get rid of the migration files. They are not needed
 Add them in gitignore

2017-03-01 19:56 UTC, meshde commented
I've removed each and every reference to Slot,Webcam,Bookings, and board.
The site and the client experiment are working perfectly
I've also added the suggested directories in the gitignore, but they still have been pushed. Could you please check if I did anything wrong with respect to the gitignore file?

2017-03-02 08:21 UTC, maheshgudi commented on .gitignore
> +migrations\
add a new line here. All files should end on a new line.

2017-03-02 08:50 UTC, maheshgudi requested changes
Need to clean up the code further.

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/admin/views.py
> +#from sbhs_server.tables.models import Board, Booking
commented code.

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/admin/views.py
> +#@login_required(redirect_field_name=None)
Commented code.

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/experiment/views.py
>  import json, datetime, os, time
Please import the modules separately as asked.

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/experiment/views.py
> +global boards
What is boards? Why are you putting that in global namespace?

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/experiment/views.py
> +    global boards
Again? Why this?

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/experiment/views.py
> +        global boards
Why?

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/experiment/views.py
> +            #boards.setHeat(0)
commented code

2017-03-02 08:50 UTC, maheshgudi commented on sbhs_server/settings.py
> +#WEBCAM_DIR = os.path.join(STATIC_ROOT, 'img/webcam/') if is_production else os.path.join(BASE_DIR, 'static/img/webcam/')
get rid of the code.

2017-03-02 17:21 UTC, meshde commented on .gitignore
> +migrations\
You mean a blank last line?

2017-03-02 17:22 UTC, meshde commented on sbhs_server/experiment/views.py
>  import json, datetime, os, time
I'm sorry, forgot about these.I'll change them right away

2017-03-02 17:33 UTC, meshde commented on sbhs_server/experiment/views.py
> +global boards
'boards' is a Sbhs object that is created when the user logs in from the client application in the initiation() method. I've declared it global as the object created during initiation() is being used in the experiment() method.

2017-03-03 12:19 UTC, maheshgudi commented on .gitignore
> +migrations\
yes

2017-03-12 18:24 UTC, meshde commented
I've made all changes that I was asked to make. The things that remain to be done include changing the admin views to display some relevant info(I haven't been told what to do about it) and integrating with yaksh module.

2017-04-26 06:15 UTC, merged

2017-04-26 06:15 UTC, rupakrokade commented
Merged mehmoods work with the base repo